-- Cleanup AcmeCloud Metatate demo fixture.

SET SETUP_ROLE = 'NAC';
SET APP_NAME = 'METATATE_APP';
SET DEMO_DATABASE = 'ACMECLOUD_DEMO';
SET DEMO_SCHEMA = 'PUBLIC';
SET DEMO_SCHEMA_FQN = $DEMO_DATABASE || '.' || $DEMO_SCHEMA;
SET CUSTOMERS_TABLE = $DEMO_SCHEMA_FQN || '.CUSTOMERS';
SET SUBSCRIPTIONS_TABLE = $DEMO_SCHEMA_FQN || '.SUBSCRIPTIONS';
SET EVENTS_TABLE = $DEMO_SCHEMA_FQN || '.PRODUCT_USAGE_EVENTS';
SET SUPPORT_TABLE = $DEMO_SCHEMA_FQN || '.SUPPORT_TICKETS';
SET EXPORTS_TABLE = $DEMO_SCHEMA_FQN || '.CUSTOMER_EXPORTS';

USE ROLE IDENTIFIER($SETUP_ROLE);
USE APPLICATION IDENTIFIER($APP_NAME);

DELETE FROM app_data.governance_decision_log
WHERE table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.deployed_transfer_rules
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.deployed_validation_rules
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.deployed_data_meaning
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.deployed_usage_rules
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.deployed_column_details
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.deployed_instructions
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);
DELETE FROM app_data.governed_tables
WHERE full_table_name IN ($CUSTOMERS_TABLE, $SUBSCRIPTIONS_TABLE, $EVENTS_TABLE, $SUPPORT_TABLE, $EXPORTS_TABLE);

USE ROLE IDENTIFIER($SETUP_ROLE);
DROP DATABASE IF EXISTS IDENTIFIER($DEMO_DATABASE);

SELECT 'AcmeCloud demo fixture removed.' AS status;

